sudo: required
services:
  - docker
before_install:
  - docker build -t shandak/docker-react -f Dockerfile.dev .
env:
  - CI="true"
language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - docker run shandak/docker-react npm run build
  - npm test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-351523127941"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"