version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #- /app/node_modules
      - ./public:/app/public
      - ./src:/app/src
      - ./build:/app/build
#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    volumes:
#      - ./public:/app/public
#      - ./src:/app/src
#    command: ["npm", "run", "test"]